### ISSUE TITLE
Functions not working (Linux, Ubuntu 16.04.1)

### ISSUE THREAD

**Issue by pat-s** [RMHogervorst/badgecreatr#26] opened 2016-10-16 10:09 UTC
## Using the CRAN version:

```
findbadges()
Error in stringr::str_match(grep("R \\(", description, value = TRUE),  : 
  subscript out of bounds
```

Same error message for `badgecreatr()`.
## Using the Github version:

```
> findbadges()
$projectstatus_readme
[1] TRUE

$licencebadge_readme
[1] FALSE

$travisbadge_readme
[1] TRUE

$codecoverage_readme
[1] FALSE

$rversion_readme
[1] TRUE

$cranbadge_readme
[1] TRUE

$packageversionbadge_readme
[1] TRUE

$last_change_readme
[1] TRUE

$licence
[1] "MIT +"

$packagename
[1] "oddsratio"

$travisfile
[1] TRUE

$codecov_in_travisfile
[1] FALSE

Warning message:
In readLines(".travis.yml") : incomplete final line found on '.travis.yml'
```

I definitely have a .travis.yml file in my wd. 
Calling the functions from the directory root of my R package.  
Path: `"~/someName/PackageName"`

**Comment by privefl** [comment] 2016-10-16 10:35
This is a duplicate of https://github.com/RMHogervorst/badgecreatr/issues/19.

You just need to add `Depends: R (>= 3.2.3)` in your description file (use the version you want), or just use this package in its github version, where this problem has been fixed.

The warning of `readLines` is really not important, if you want to remove it, just add a line with nothing at the end of your `.travis.yml`.

**Comment by pat-s** [comment] 2016-10-16 20:11
@privefl thanks for clarification!

**Comment by RMHogervorst** [comment] 2016-10-17 08:33
I will update the cran package in a month or so.

**Closed as completed** 2017-04-12 15:08 UTC
